name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
          pip install pytest

      - name: Lint (pre-commit)
        run: python -m pre_commit run --all-files --show-diff-on-failure

      - name: Run tests
        run: python -m pytest -q
